
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build || echo "No build script"
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
